version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      kubernetes:
        patterns:
          - k8s.io/*
      aws:
        patterns:
          - github.com/aws/aws-sdk-go-v2*
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
