services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

  nats:
    image: nats:latest
    volumes:
      - nats:/data
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--js"
      - "--sd=/data"
      - "--http_port=8222"

volumes:
  minio: {}
  nats: {}
