// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Download provides a mock function with given fields: ctx, app, w
func (_m *MockClient) Download(ctx context.Context, app string, w io.Writer) error {
	ret := _m.Called(ctx, app, w)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Writer) error); ok {
		r0 = rf(ctx, app, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockClient_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - app string
//   - w io.Writer
func (_e *MockClient_Expecter) Download(ctx interface{}, app interface{}, w interface{}) *MockClient_Download_Call {
	return &MockClient_Download_Call{Call: _e.mock.On("Download", ctx, app, w)}
}

func (_c *MockClient_Download_Call) Run(run func(ctx context.Context, app string, w io.Writer)) *MockClient_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Writer))
	})
	return _c
}

func (_c *MockClient_Download_Call) Return(_a0 error) *MockClient_Download_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Download_Call) RunAndReturn(run func(context.Context, string, io.Writer) error) *MockClient_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Profile provides a mock function with given fields: ctx, src, duration
func (_m *MockClient) Profile(ctx context.Context, src string, duration time.Duration) (io.ReadCloser, error) {
	ret := _m.Called(ctx, src, duration)

	if len(ret) == 0 {
		panic("no return value specified for Profile")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (io.ReadCloser, error)); ok {
		return rf(ctx, src, duration)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) io.ReadCloser); ok {
		r0 = rf(ctx, src, duration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, src, duration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Profile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Profile'
type MockClient_Profile_Call struct {
	*mock.Call
}

// Profile is a helper method to define mock.On call
//   - ctx context.Context
//   - src string
//   - duration time.Duration
func (_e *MockClient_Expecter) Profile(ctx interface{}, src interface{}, duration interface{}) *MockClient_Profile_Call {
	return &MockClient_Profile_Call{Call: _e.mock.On("Profile", ctx, src, duration)}
}

func (_c *MockClient_Profile_Call) Run(run func(ctx context.Context, src string, duration time.Duration)) *MockClient_Profile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockClient_Profile_Call) Return(_a0 io.ReadCloser, _a1 error) *MockClient_Profile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Profile_Call) RunAndReturn(run func(context.Context, string, time.Duration) (io.ReadCloser, error)) *MockClient_Profile_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, app, r
func (_m *MockClient) Upload(ctx context.Context, app string, r io.Reader) error {
	ret := _m.Called(ctx, app, r)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, app, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockClient_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - app string
//   - r io.Reader
func (_e *MockClient_Expecter) Upload(ctx interface{}, app interface{}, r interface{}) *MockClient_Upload_Call {
	return &MockClient_Upload_Call{Call: _e.mock.On("Upload", ctx, app, r)}
}

func (_c *MockClient_Upload_Call) Run(run func(ctx context.Context, app string, r io.Reader)) *MockClient_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader))
	})
	return _c
}

func (_c *MockClient_Upload_Call) Return(_a0 error) *MockClient_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader) error) *MockClient_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
