// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	target "github.com/davidsbond/autopgo/internal/target"
)

// MockTargetSource is an autogenerated mock type for the TargetSource type
type MockTargetSource struct {
	mock.Mock
}

type MockTargetSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTargetSource) EXPECT() *MockTargetSource_Expecter {
	return &MockTargetSource_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx
func (_m *MockTargetSource) List(ctx context.Context) ([]target.Target, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []target.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]target.Target, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []target.Target); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]target.Target)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTargetSource_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTargetSource_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTargetSource_Expecter) List(ctx interface{}) *MockTargetSource_List_Call {
	return &MockTargetSource_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTargetSource_List_Call) Run(run func(ctx context.Context)) *MockTargetSource_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTargetSource_List_Call) Return(_a0 []target.Target, _a1 error) *MockTargetSource_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTargetSource_List_Call) RunAndReturn(run func(context.Context) ([]target.Target, error)) *MockTargetSource_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTargetSource creates a new instance of MockTargetSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTargetSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTargetSource {
	mock := &MockTargetSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
